import { Button } from "@/components/ui/button";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Nav from "~/components/Nav";
import { api } from "~/utils/api";
import Post from "~/components/Post";
import Upload from "~/components/Upload";

export default function Home() {
  const userQuery = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-between sm:flex-row sm:justify-normal">
        <div className="top-0  hidden h-screen w-60 flex-col sm:sticky sm:flex ">
          <h1 className="mx-9 my-4 w-min border border-white px-10 pb-0 text-4xl">
            ONLY NOTES
          </h1>
          <Nav />
        </div>

        <div className="container flex w-full flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex w-full flex-col items-center gap-2">
            <Upload />
            {!userQuery.data && <h1>Nie znaleziono postów</h1>}
            {userQuery.data?.map((post) => (
              <Post
                comments={post.comments.map((comment) => comment.id)}
                id={post.id}
                bookmarks={post.bookmarks.map((bookmark) => bookmark.id)}
                key={post.id}
                text={post.text}
                user={post.userId}
                likes={post.likes.map((like) => like.id)}
                images={post.images.map((image) => image.remoteId)}
              />
            ))}
          </div>
        </div>
        <div className="block sm:hidden">
          <Nav />
        </div>
      </main>
    </>
  );
}
