import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SendHorizonal } from "lucide-react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import Nav from "~/components/Nav";
import Post from "~/components/Post";

import { api } from "~/utils/api";

export default function Search() {
  const router = useRouter();
  const [query, setQuery] = useState("");
  let slug = router.query.search;
  if (typeof slug !== "string") {
    slug = undefined;
  }

  const posts = api.posts.search.useQuery({
    query: slug ?? "ls;dfkjasdfijwpo",
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-between sm:flex-row sm:justify-normal">
        <div className="top-0  hidden h-screen w-60 flex-col sm:sticky sm:flex ">
          <h1 className="mx-9 my-4 w-min border border-white px-10 pb-0 text-4xl">
            ONLY NOTES
          </h1>
          <Nav />
        </div>

        <div className="container flex w-full flex-col gap-12 px-4 py-4 pb-16 ">
          <div className="flex w-full items-center justify-center  gap-2">
            <Input
              onKeyDown={async (e) => {
                if (e.key === "Enter") {
                  router.push(`/search/${query}`);
                }
              }}
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Wyszukaj posty, bądź użytkowników"
              className="h-14 w-full bg-zinc-900"
            />
            <Button
              className="h-full"
              onClick={() => {
                router.push(`/search/${query}`);
              }}
            >
              <SendHorizonal />
            </Button>
          </div>
          <div className="flex w-full flex-col items-center gap-6">
            <p className="mb-4 text-4xl font-bold leading-7  [&:not(:first-child)]:mt-6">
              Wyniki Wyszukiwania: {slug}
            </p>
            {!posts.data && <h1>Nie znaleziono postów</h1>}
            {posts.data?.map((post) => (
              <Post
                comments={post.comments.map((comment) => comment.id)}
                id={post.id}
                bookmarks={post.bookmarks.map((bookmark) => bookmark.id)}
                key={post.id}
                text={post.text}
                user={post.userId}
                likes={post.likes.map((like) => like.id)}
                images={post.images.map((image) => image.remoteId)}
              />
            ))}
          </div>
        </div>
        <div className="block sm:hidden">
          <Nav />
        </div>
      </main>
    </>
  );
}
